### ISSUE TITLE
Extension opens a different test file

### ISSUE THREAD

**Issue by msramos** [samuelpordeus/vscode-elixir-test#19]
I have the following project structure:

```
lib/
  api.ex
tools/
  api.ex
```

The `lib/api.ex` file doesn't have any test file. But if I try to open it, the extension will open the test for `tools/api.ex`

**Comment by w-sanches** [comment]
Just out of curiosity, what is the difference in naming from both files?

**Comment by samuelpordeus** [comment]
@w-sanches I don't know if you are talking about the module name, but it was something like this👇
```
defmodule Context.Api do
...
end

defmodule Api do
...
end
```
