### ISSUE TITLE
Run eslint on TravisCI

### ISSUE THREAD

**Issue by mracos** [samuelpordeus/vscode-elixir-test#28]
As to enforce a consistent style.

**Comment by marcelinol** [comment]
hi @mracos I noticed that the project has eslint already: https://github.com/samuelpordeus/vscode-elixir-test/blob/6413275fe85570f79399908231d33decd918c5b9/package.json#L60

Does this issue mean to set it up on TravisCI or some other tool, or is it done as expected already and the issue should be closed?

**Comment by mracos** [comment]
My bad @marcelinol! I meant to add to TravisCI yeah. 😅
