### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by samuelpordeus** [samuelpordeus/vscode-elixir-test#3]
I didn't touch the test suite that the vs-code extensions boilerplate gave me. Would be really nice to have some tests kicking on 😃

**Comment by samuelpordeus** [comment]
@paulo-silva thanks for resolving #4, but now we need the tests 😂

**Comment by paulo-silva** [comment]
@samuelpordeus sure 🤣, let's start setting up Jest 😄. I'll submit a PR with it
