### ISSUE TITLE
Scroll the terminal when a new test command is run

### ISSUE THREAD

**Issue by mracos** [samuelpordeus/vscode-elixir-test#40]
If we scroll the terminal up it is not scrolled back down if we run another test command.
It is a nit but I think it's a nice UX detail.

<details>
<summary> GIF </summary>
<img src="https://user-images.githubusercontent.com/14015177/66233392-a3a3ac00-e6c1-11e9-8c78-f50daafc5939.gif" />
</details>

**Comment by ricardoruwer** [comment]
Or we can clear the terminal before running the test...

**Comment by mracos** [comment]
My only concern is with losing the information from the previous run, if clearing the screen still allows us to scroll back I'm ok with it. :smile:

**Comment by msramos** [comment]
Hey @mracos ✋ 

[I've added a new option to the extension](https://github.com/samuelpordeus/vscode-elixir-test/commit/5b8a1087c4b737555a10570e47b53fb57d7dc842) that allow custom commands to run before tests. This way you can set a `clear` command (or anything you want).

Although it's not what you suggested, is the only think I can think of - vscode doesn't have an API to manipulate the cursor from the integrated terminal.

It will be included in the next release!
