### ISSUE TITLE
Add a `when` in the keybinding

### ISSUE THREAD

**Issue by ricardoruwer** [samuelpordeus/vscode-elixir-test#42]
The value could be `editorTextFocus && editorLangId == 'elixir'`

**Comment by mracos** [comment]
I'm not sure I understand what you meant by this issue. 🤔

**Comment by samuelpordeus** [comment]
@mracos if we associate `when` with the keybindings the commands will only be issued if the target is an elixir file.

**Comment by mracos** [comment]
Ahhhh, I see. Is some kind of "filter" provided by vscode, right?

**Comment by GuSilverFlame** [comment]
yes, but Elixir isn't officially supported so it may cause some bugs
https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers

**Comment by ricardoruwer** [comment]
Not sure, but I think you have to install the `ElixirLS` to have this `elixir` language, right?
