### ISSUE TITLE
Run tests in folder

### ISSUE THREAD

**Issue by ricardoruwer** [samuelpordeus/vscode-elixir-test#43]
I saw it in the extension `Rails Test Runner` and I think it'll be a good idea to implement it in this extension as well, take a look:

It appears when I right-click in some folder of the project

![image](https://user-images.githubusercontent.com/7904540/66432475-87bb4580-e9f4-11e9-8647-863cbc5fd0cd.png)

**Comment by gVirtu** [comment]
I'm giving this one a try! :slightly_smiling_face:
