### ISSUE TITLE
 keyword argument must be followed by space after: exs:

### ISSUE THREAD

**Issue by mikepc** [samuelpordeus/vscode-elixir-test#46]
I'm receiving this error whenever I run test at cursor

**Comment by mikepc** [comment]
And alternatively:
Paths given to "mix test" did not match any directory/file: apps/path/to/test/accounts_test.exs:22

If it helps, this is an umbrella elixir project

**Comment by mracos** [comment]
Do you have any `test` alias defined in your `mix.exs`? Maybe you have a typo or something like that?

**Comment by samuelpordeus** [comment]
I'm closing this one, if you have anything more to add about this issue, feel free to ping us.
