### ISSUE TITLE
Default keybinding to run tests conflicts with built-in shortcut

### ISSUE THREAD

**Issue by brainlid** [samuelpordeus/vscode-elixir-test#48]
On Linux and Windows, the keyboard binding `ctrl + shift + k` is already mapped by default in VS Code as "Delete Line". I use this shortcut all the time. I'm on Linux.

- https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf
- https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

I just installed the Elixir Test extension and it broke my keybinding.

Consider changing the default keybinding? Otherwise users have to know to re-map it.

**Comment by samuelpordeus** [comment]
@brainlid thanks for opening the issue, we should definitely change it.

**Comment by brainlid** [comment]
Looks like you guys fixed it! :heart:

**Comment by brainlid** [comment]
Sorry. My mistake. It's still an issue.

**Comment by vsyrovat** [comment]
It's true, by default combination `Ctrl+Shift+K` binded to "delete line", but there is not significant influence to work abilities because line deleting is possible with `Shift+Del`.

**Comment by focused** [comment]
> It's true, by default combination `Ctrl+Shift+K` binded to "delete line", but there is not significant influence to work abilities because line deleting is also possible with `Shift+Del`.

On macbook's keyboard there is a `Shift+Backspace` and it's binded to `deleteLeft` by default, to use `Shift+Delete` I need to press `Fn` key also, it's very inconvenient.

**Comment by ricardoruwer** [comment]
Feel free to open a PR
-> https://github.com/samuelpordeus/vscode-elixir-test/blob/master/package.json#L58

**Comment by brainlid** [comment]
> It's true, by default combination `Ctrl+Shift+K` binded to "delete line", but there is not significant influence to work abilities because line deleting is also possible with `Shift+Del`.

`Shift+Del` isn't a "delete line" it's a "cut". So it removes the line but modifies the copy buffer.
