### ISSUE TITLE
How to run last test?

### ISSUE THREAD

**Issue by diegonogueira** [samuelpordeus/vscode-elixir-test#49]
There is a shortcut to repeat the last test?

thanks

**Comment by samuelpordeus** [comment]
@diegonogueira great suggestion, feel free to open a PR 🙂

**Comment by tomekowal** [comment]
Hey! I could open a PR for this feature sometime next week.
I have yet to make any vscode extensions so I would appreciate some guidance.
Is there a standard solution for this kind of behaviour?
I imagine I would need to:
- find some "global variable" that holds what elixir test was run last (entire file, line, other...)
- for each command "save" to that global variable that this was the last run command
- add a command for re-running that reads that global variable and selects what to run

But I am not sure what is the correct place for storing the information about the last run test or how to print some nice debug message if someone tries this command in a new session before running anything else.
I'll try to dig through VSCode docs, but if there is more than one way to do it, it would be nice to know which one the maintainers prefer :)

**Comment by msramos** [comment]
@diegonogueira @samuelpordeus @tomekowal [I just added this feature on master](https://github.com/samuelpordeus/vscode-elixir-test/commit/82104952b6322d8fda88415a96db56616c94dd2c). It will be included in the next release.

Thanks for everyone's input!
