### ISSUE TITLE
Would be convenient to manage the create test template via config

### ISSUE THREAD

**Issue by sitch** [samuelpordeus/vscode-elixir-test#54]
https://github.com/samuelpordeus/vscode-elixir-test/blob/b18e91369d9f181c7017ee734c95cc30fd5a5385/src/commands/jumpToTest.js#L32

Even just using something like
```elixir
defmodule <%= @module_name %> do
  @moduledoc """
  Test for `<%= @module_name %>`.
  """
  
  use ExUnit.Case, async: true

  alias <%= @module_name %> 

<% for {module, fun, arity} <- @mfas do %> 
  describe ".<%= fun_name %>/<%= arity %>" do
    test "given valid params" do
      assert <%= @module_alias %>.<%= fun_name %>() == true
    end
  end
<% end>
end
```

**Comment by sitch** [comment]
Could have a simple regex to just pull out the `def` calls and just set the arity to 0 by default
```js
const defRegex = /\n\s*def\s([a-z_\?]+)/
```

**Comment by sitch** [comment]
At the very least just pulling a template string out of the config or defaulting to the current one.. Just nice bc i usually include @moduledoc and even just one describe block saves a bit of time

**Comment by samuelpordeus** [comment]
@sitch sorry for the delayed answer. Sounds like a good thing to do. Can you open a PR for that?

**Comment by sitch** [comment]
I ended up writing more sophisticated test generators and templates dispatch based on folder structure / the presence of certain use macros which are likely coupled to some of my personal implementations, and would require some introspection with elixir

I could probably update the current template method fn and add the regex above to pull out the defs or default to some example text in the even there are no defs.  Won't be able to get around to it for a little while though.

Moving forward though, probably the most user friendly is to add a `template_dir` config option, which, if present and contains only one template it uses that, and if it contains more than one templates, then open an additional dialog option to select the template of your choice

**Comment by samuelpordeus** [comment]
I'm closing this one for now. If there's any interesting in opening a PR we can re-open it 😄
