### ISSUE TITLE
Connect to vscode-test-explorer

### ISSUE THREAD

**Issue by obsidienne** [samuelpordeus/vscode-elixir-test#55]
Hi,

[vscode test explorer](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) is a cool extension to visualize the tests.

Is it possible to connected this extension to it ?

Thanks

**Comment by samuelpordeus** [comment]
@obsidienne Sounds cool. Do you have interest in taking a shot at it? 😄

**Comment by obsidienne** [comment]
Hi,

Why not, but I don’t know how to create and test  vscode Plugins

**Comment by RoyalMist** [comment]
Hello I was thinking about this, I will try to start it soon.
By the way Samuel can you update the plugin on the code marketplace for the test template file please :)

**Comment by samuelpordeus** [comment]
@RoyalMist Hey, Royal! Done that today. Thanks for hopping into this issue too 😄

**Comment by msramos** [comment]
@obsidienne this plugin is now deprecated. VSCode added official UI and API for tests starting from `1.59`. I'll close this issue for now, but I plan to integrate the extension with VSCode in the future.
