### ISSUE TITLE
Create either `module_test.exs` or `module.ex` conditionally based on the caller file

### ISSUE THREAD

**Issue by sitch** [samuelpordeus/vscode-elixir-test#56]
### Execute from `module.ex`
- Write file  `module_test.exs` :heavy_check_mark: 

### Execute from `module_test.exs`
- Write file  `module_test_test.exs` :x: 

Expected:
- Write file  `module.ex` :heavy_check_mark:

**Comment by samuelpordeus** [comment]
That's an enhancement that I'm honestly not that interested in doing by myself, but for anyone that is reading this, feel free to do it ❤️

**Comment by eprothro** [comment]
We'd love to see this as well FWIW. Will open a PR if we get the time.

**Comment by msramos** [comment]
@sitch @samuelpordeus @eprothro [I've added this feature to the main branch](https://github.com/samuelpordeus/vscode-elixir-test/commit/722332a8b9d994d45119fcb6b438a2446f165f60). It will be included in the next release!

Thanks for the suggestions ❤️

**Comment by eprothro** [comment]
So excited! When do you expect to release?

**Comment by msramos** [comment]
@eprothro already released. Feel free to update the extension from VSCode!
