### ISSUE TITLE
Add to Open VSX Registry

### ISSUE THREAD

**Issue by baldwindavid** [samuelpordeus/vscode-elixir-test#59]
It would be great if this were listed on the [Open VSX Registry](https://open-vsx.org/). This allows other editors such as [Oni Vim](https://onivim.io/) use the extension. I think anyone can add this to the registry, but this may be something that you want to control.

**Comment by samuelpordeus** [comment]
Hi, @baldwindavid. I'm going to take a look at it on the weekend. Didn't know about that. Thanks!

**Comment by samuelpordeus** [comment]
Done @baldwindavid! Sorry for the delay, ended up forgetting about it 😬 

it's listed here: https://open-vsx.org/extension/samuel-pordeus/elixir-test

**Comment by baldwindavid** [comment]
Cool, thanks. I installed it, but I _think_ OniVim needs to be developed a bit more before it will work with it. Regardless, thanks for adding to the registry and I look forward to using it in the future.
