### ISSUE TITLE
Consider more "jumps"? Maybe in a new extension?

### ISSUE THREAD

**Issue by zorn** [samuelpordeus/vscode-elixir-test#63]
I just discovered this extension over the weekend and am loving it.

I do wonder if there is value in moving the jumping behavior into it's own extension? Thinking aloud, maybe I'd want to jump from a controller to a view or from a method to a template?

Not sure if I'll have an opportunity to help out but wanted to share my thoughts. Thanks again!

**Comment by samuelpordeus** [comment]
This is interesting. I will label it as an `enhancement` and close it. I definitely think it would be better suited as a separate extension 😬
