### ISSUE TITLE
Handle terminal already running command / multiple terminals

### ISSUE THREAD

**Issue by dantswain** [samuelpordeus/vscode-elixir-test#65]
Hi!  This extension is super handy!

This is just a small improvement suggestion - I'm not familiar with extension development so I'm not sure how difficult it would be.

## Use case
I often have two terminal panes open, and one of them is often already running a command - `iex`, `psql`, etc.  I'm not sure how this plugin chooses which terminal to use (first, maybe?) but if I execute any of the "run test" commands, it has a chance to try to inject the `mix test ...` command into my running application. 

## Suggested changes
* It would probably be a good idea to have the extension refuse to insert text into a terminal pane when that terminal pane is already running a command (other than the shell).  One can imagine potentially disastrous scenarios where commands are executed in unexpected environments.
* If more than one terminal is open, perhaps loop through the open terminals until a "valid candidate" (i.e., not running another command already) is found.

**Comment by samuelpordeus** [comment]
I honestly don't know how difficult it would be 😅  – but the suggestion seems reasonable to me. If anyone is interested feel free to do it.

**Comment by msramos** [comment]
@dantswain unfortunatelly VSCode does not provide and API to detect if the terminal is running a command or not, so I'm afraid it's not possible to do this.
