### ISSUE TITLE
Support multiple projects

### ISSUE THREAD

**Issue by bengro** [samuelpordeus/vscode-elixir-test#69]
I'm working in a multi-project setting, like so:

```
root (no mix file)
- ProjectA (mix project)
- ProjectB (mix project)
- ProjectC (no mix project)
```

When I run the tests in `ProjectA` or `ProjectB` I'm getting:
`** (Mix) Could not find a Mix.Project, please ensure you are running Mix in a directory with a mix.exs file`

I'm assuming this is because it's looking for the mix file in the root.

When I cd into the project directory it works. It's just a shame I have to switch back and forth.

It would be great to support mono repos with multiple mix projects in it.

Thoughts?

**Comment by samuelpordeus** [comment]
Agreed. Not my use case, but it would be nice to have. If you are interested, feel free to open a PR for it 🙂

**Comment by msramos** [comment]
@bengro @samuelpordeus [I've added support for workspaces with multiple projects on the main branch](https://github.com/samuelpordeus/vscode-elixir-test/commit/b6b2c847c4b1a4474c0fbdf1924eca59e7cd0850). It will be included in the next release.

Thanks for the suggestion!
