### ISSUE TITLE
Jump falsely shows pop-up "create test" in workspace

### ISSUE THREAD

**Issue by bengro** [samuelpordeus/vscode-elixir-test#70]
Love the extension.

I'm running into a bug when I'm using the extension in a vs workspace.

When I jump between implementation and code, the pop-up ("Do you want to create test") shows up every time even though an exist already exists. 

When I click create, it switches to the implementation just fine.

See here:
https://recordit.co/NX9OXo8MkL

**Comment by samuelpordeus** [comment]
@bengro released with `1.7.1` 😬
