### ISSUE TITLE
Prefix MIX_ENV variable for mix test command

### ISSUE THREAD

**Issue by hackvan** [samuelpordeus/vscode-elixir-test#79]
Is there an actual way to set a `MIX_ENV=test` prefix before the `mix test` command?

**Comment by antedeguemon** [comment]
AFAIK this extension doesn't support configuring a custom `mix test` command.

Even though `MIX_ENV=test` is the default environment for `mix test`, I think can be useful to allow custom commands. So, +1 on the feature request 🙈

**Comment by samuelpordeus** [comment]
@hackvan @antedeguemon hi folks, replying with less than 365 days! what a lead time!

i'm planning to give some love to the extension this month, will try to include that, but feel free to send a pr!

**Comment by msramos** [comment]
@hackvan @antedeguemon @samuelpordeus I included the option `vscode-elixir-test.mixEnv` that will automatically inject `MIX_ENV` when present.

It will be included in the next release.

Thanks for the suggestion!
